version: '3.8'

services:
  rag-api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - searxng
    environment:
      - MISTRAL_API_KEY=${MISTRAL_API_KEY}

  searxng:
    image: searxng/searxng:latest
    ports:
      - "8080:8080"
    environment:
      - BASE_URL=http://localhost:8080/
      - INSTANCE_NAME=RAG-Search
    volumes:
      - ./searxng:/etc/searxng
    depends_on:
      - redis

  redis:
    image: redis:latest
    volumes:
      - redis_data:/data

volumes:
  redis_data:
